### ISSUE TITLE
Awesome Book Peer review

### ISSUE THREAD

**Issue by frempongdev** [coderacheal/Awesome-Books#1]
After reviewing your project we found the following issues:
- Readme.md file is not professional. Kindly stick to the [Microverse Readme Template.](https://github.com/microverseinc/readme-template)
- After refreshing the page your local storage does not return the added inputs.
https://github.com/coderacheal/Awesome-Books/blob/removeFunction/script.js#L57 
Please check the above line to rectify the issue. 

Kindly refer to [this link](https://www.javatpoint.com/javascript-localstorage#:~:text=LocalStorage%20is%20a%20data%20storage,after%20closing%20the%20browser%20window.) for reference on local storage.

**Comment by coderacheal** [comment]
Issue fixed
